### ISSUE TITLE
Tag 0.8.2 missing from Packagist

### ISSUE THREAD

**Issue by benr77** [composer-unused/composer-unused-plugin#10]
Version 0.8.2 has been created as a release, but this is not available via Packagist, which is only showing up to 0.8.1.

https://packagist.org/packages/composer-unused/composer-unused-plugin

Thanks

**Comment by icanhazstring** [comment]
Hi thanks for the heads-up. Will check on that.

**Comment by icanhazstring** [comment]
I had to remove version 0.8.2 from packagist as this was completely broken.
You can still refer to the newest/next release.
